---
dbconfig:
  collection: data_governance
  # Docker
  dburl: "mongodb://mongo-dg:mongo-dg-artefacts@mongo"
  # Local
#  dburl: "mongodb://mongo-dg:mongo-dg-artefacts@localhost"
  port: ":27017"

#mysqlconfig:
#  dburl: "mysql-db"
#  port: ":3306"
#  user: "root"
#  password: "example"
#  database: "results"

minioconfig:
#  dburl: "127.0.0.1"
  dburl: "minio"
  port: ":9000"
  accesskey: "fastapi"
  secretkey: "fastapi_secretkey"

keycloak:
  #  Docker
  url: http://kc:8080/auth #Auth with reverse proxy
  introspect_url: http://localhost/auth #Auth with reverse proxy
  # Local
#  url: http://localhost/auth
  realm: fml
  api_client_id: fml-api
  api_client_secret: qhwXVzDfriZ7hb9wRAxycxeES9C1ppLb # secret only for development purposes
  admin_client_id: admin-cli
  admin_client_secret: S5Z5IEmqqJFqBcrkaSCyLoxF6Cue0S0t # secret only for development purposes

metadata:
  # docker
  host: metadata-api
  #local
#  host: localhost
  port: 5001